# Generated by Django 3.1.3 on 2021-02-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metering_database', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
